# Generated by Django 3.2.5 on 2021-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
